//Product state types
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY";
export const SET_ACTIVE_CATEGORY_PRODUCTS = "SET_ACTIVE_CATEGORY_PRODUCTS";
export const SET_SINGLE_PRODUCT = "SET_SINGLE_PRODUCT";
export const SET_PRODUCT_LOADING = "SET_PRODUCT_LOADING";

//Cart state types
export  const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_CART_AMOUNT = 'CHANGE_CART_AMOUNT';
export const CLEAR_CART = 'CLEAR_CART';

//Checkout state types
export const SET_CHECKOUT_FIELDS = 'SET_CHECKOUT_FIELDS'
